### ISSUE TITLE
Mailcatcher image shows warning

### ISSUE THREAD

**Issue by drpayyne** [luancschmitz/docker-magento-mac-m1#3]
**Description**

The mailcatcher container shows a warning like below in the Docker Desktop dashboard. Is this image supported for arm64? I don't see ARM support listed in it's Docker Hub page - https://registry.hub.docker.com/r/schickling/mailcatcher/tags?page=1&ordering=last_updated

![image](https://user-images.githubusercontent.com/22623301/129940678-dfc0986e-9a59-4e73-8084-8ed065aa4b07.png)

**Comment by luancschmitz** [comment]
HI @drpayyne.

this image don't support arm64, but run with emulation without problems. 

I need to take some time to see if I can exchange this image for one that supports it.
I will change the mailchatcher image to this one:
https://registry.hub.docker.com/r/sj26/mailcatcher
(I found this one now in a quick search.)
But first I need to see if it will work normally, if so I will make the change.

**Comment by drpayyne** [comment]
Thanks @luancschmitz, let me also test some lightweight alternatives. Thanks for your response!

**Comment by luancschmitz** [comment]
I solved the problem...
I changed the mailcatcher to the one I mentioned.

I have tested sending email and it is working normally.

Thanks for reporting the bug.
