### ISSUE TITLE
Issue with access keys and Composer during installation

### ISSUE THREAD

**Issue by MrNovember22** [luancschmitz/docker-magento-mac-m1#7]
**Description**
During setup(run command bin/setup magento2.test) on my MacBook Air M1 I've got these errors with keys and composer
![image](https://user-images.githubusercontent.com/23629776/131788188-470713ec-b658-444d-8eba-cc6d3147fa9f.png)
I've tried to use Composer (version 2.1.6 or 1.10.12)

I generated access keys on https://marketplace.magento.com/customer/accessKeys/ but it does not help.

Also I tried to use this hint 'Use the option --with-all-dependencies (-W)' and it also does not help. 
Please give me some tips to finish installation

**Comment by luancschmitz** [comment]
Hi, thanks for opening this issue.
I actually tested it here and the bin/setup wasn't working.
I updated the code again with the mark master, and by testing it is now ok.
Please test again and let me know if you are now able to climb a magento 2 store.

This issue #9 solved the problem

**Comment by MrNovember22** [comment]
@luancschmitz Hey, actually today I've fixed my issue. So..
1. I ran bin/bash and got to the magento folder inside container and ran 'composer install'
2. after that I had an issue with scrip again, but I commented line №29 bin/clinotty composer update and executed the script successfully.
So, now Magento is working fine on my local, thanks for feedback! maybe this info will help someone.

**Comment by luancschmitz** [comment]
thanks for the report, and sorry for having only seen this issue now.
I believe it won't happen again, as I fixed the problem and bin/setup is now working perfectly.
I will close this issue, but if necessary, you can open another one.
